# Generated by Django 3.1.5 on 2021-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_auto_20210125_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
